name: Update WakaTime Stats in README

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Profile Readme Development Stats
      uses: anmol098/waka-readme-stats@v4
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
    
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m 'Updated WakaTime stats in README' || echo "No changes to commit"
        git push
